### ISSUE TITLE
Trouble Getting Started

### ISSUE THREAD

**Issue by jpwkeeper** [juliusfriedman/net7mma_core#11]
I apologize up front since this is certainly a newbie question, but I have no experience with RTP coming into this.

I'm trying to understand how this library works, but I can't seem to find any complete, simple examples.  The example on CodeProject is difficult to follow in the text and I can't seem to find a place to download the example.  I suspect if I was more experienced in RTP I'd understand it better.

I'm trying to make a simple peer-to-peer voice chat application as a learning tool.  Part of the problem is that this is different than the more common Media Server examples.  I can handle every other aspect of the application (UI, audio capture, audio playback, etc) without issue, but I'm being encouraged by colleagues to try to use RTP instead of just multicasting audio data.

I've seen references in other issues to examples, but I cannot seem to find them.  Can you point me to some examples of using net7mma that can at least get me off the ground?

**Comment by juliusfriedman** [comment]
There are enough examples and this issue is not formatted in a way in which I desire to help you. If you cannot get where you need to be with the illustrated examples and articles I fear there is nothing I can do to help you and to present such as an issue would otherwise be moot.

Good day and thank you for your interest in the library!

**Comment by jpwkeeper** [comment]
Can you link me some of these examples?  I've had a hard time finding anything but the CodeProject example.

**Comment by juliusfriedman** [comment]
Check https://github.com/juliusfriedman/net7mma_core/tree/master/UnitTests

**Comment by jpwkeeper** [comment]
I've been going through the Unit Tests, but I'm not getting very far.  Perhaps I'm just not seeing your overarching vision here.  Most of the unit tests, as you would expect, don't ever set up a complete end-to-end working system, but create parts of the system then pick them apart.

All I'm trying to do is to use your library to construct an extremely basic test app where two clients running on two different systems can send audio to each other.  Do I need each system to have a Server and a Client?  Can they be both just Clients?  How do I create a session for them?  How do I get the traffic onto Multicast?  What steps do each client need to take to join or leave that session?

Is it perhaps that this isn't what this library was designed for?  The one example I can find on CodeProject is a media server example.  Just in the FYI, is there any reason why the source code for that example isn't available?

The big problem I'm running into is that most of the examples were in the Discussion section of the Codeplex repo, which is now inaccessible (I have the repo downloaded, but sifting through the JSON without a viewer is less than ideal).

P.S.  I'm sorry to hear about your dog.  That was pretty low on your neighbor's part.

**Comment by juliusfriedman** [comment]
I am unfortunately not here to answer your questions on how to achieve the most basic form of communication (using RTP, RTSP et al). I will fix defects in the library or consult on its application. Beyond that I don't know what you want from me. I never even graduated from High School let alone went to a University.
Thank you for your otherwise kind words and concerns. Best of luck in your future endeavors.
Regards

**Comment by jpwkeeper** [comment]
I never went to University either.

Define what you mean by "consult on its application".  Are you saying you'll only consult on a paid basis?

I'd be willing to contribute my example app to the repository at the end of all of this.  Having a clean, concise example in the repo would help a lot of developers get started with RTP in today's managed environment.

**Comment by juliusfriedman** [comment]
Send me an email with an invitation and I will accept if I have time; after 5 PM EST works best for me. Regards

**Comment by jpwkeeper** [comment]
How would you like to meet (phone, zoom, Google Meet, Teams)?  I can make 5PM EST.

**Comment by juliusfriedman** [comment]
Sorry have been busy enough and not smoking enough weed. Probably now would be good otherwise after 5PM Tomorrow et al. Hope to talk to you soon! Regards.

**Comment by jpwkeeper** [comment]
Let’s put this on the back burner for now.  I’m not sure your library and my goals are compatible, so I’m going back to a more basic RTP implementation for now.  I or my colleagues may revisit this at a later date.

**Comment by juliusfriedman** [comment]
Sounds about right I guess; To each their own individualistic and unique approach; Few are those who can feel with their own hearts and yet see with their own eyes. 

Best of luck in your future endeavorz
