### ISSUE TITLE
Distortion while sending frames from EmguCV (customer frame)

### ISSUE THREAD

**Issue by chauhan19911** [juliusfriedman/net7mma_core#12]
Hi, I'm facing problem while sending frames captured from external source like EmguCV
This is my code to create server and to add source
```

 //Create the server optionally specifying the port to listen on
            server = new Media.Rtsp.RtspServer(IPAddress.Parse("192.168.31.173"), 8081);
            _mirror = new RFC2435Media("channel_1", null, false, testFrame.Width, testFrame.Height, false)
            {
                m_ForceTCP = true,
            };
            if (server.TryAddMedia(_mirror))
            {
                server.Start();
                foreach (var item in server.MediaStreams)
                {
                    item.Start();
                    Console.WriteLine(item.IsReady);
                    Console.WriteLine(item.State);
                }
            }
```

Code where I'm setting frame
`_mirror.Packetize(frame);`
**where frame is bitmap frame coming in 30 fps**

accessing using **rtsp://192.168.31.173:8081/live/channel_1** from **VLC**

Now, I'm getting my web camera frame in VLC through the rtsp server but that frame is distorted or too much flickering.

**Comment by juliusfriedman** [comment]
What do you want me to do about what sounds to be like re-transmission or re-ordering or perhaps packet loss?

**Comment by juliusfriedman** [comment]
1) Try using a lower default quality, something below 50 e.g. 45.
2) Try to capute the sending and the loss (you should have 2 packet caputes sent and receieved), post those here and I will take a look.
