### ISSUE TITLE
RTMP Relay Server

### ISSUE THREAD

**Issue by f135ta** [juliusfriedman/net7mma_core#2]
Hi,

I'm trying to use this as a relay server so I can ingest streams from 3rd parties and push that back and forth between Azure Media Services..

Is the RTMP client/server possible with this?

**Comment by juliusfriedman** [comment]
Just as a FYI its possible but not implemented and would require some work to get right, since RTMP isn't really a goal of mine right now I closed this issue, please feel free to re-open if you feel like this library is going to help you more than existing RTMP resources already out there.
