### ISSUE TITLE
How to use RtpClient to receive rtp data only,we don't care aboub rtcp,rtsp,

### ISSUE THREAD

**Issue by denniste** [juliusfriedman/net7mma_core#3]
How to use RtpClient to receive RTP(over udp) stream data only, we does not know the remote IP address, only binds to the local  port( (such as 5000 /IPAddress.Any), and does not care about RTCP/RTSP, etc.
Or use another library?

**Comment by juliusfriedman** [comment]
This question is invalid, just don't handle the events?

**Comment by juliusfriedman** [comment]
You can creat a RtpClient from a SessionDescription or plainly in code and it will recieve data, you just need to handle the events you are interested in if Rtcp is sent it will be hanlded for you automatically unless you disable Rtcp on the RtpClient's TransportContext.

Please let me know if you need anything else.
