### ISSUE TITLE
Unity3D Integration

### ISSUE THREAD

**Issue by mericgeren** [juliusfriedman/net7mma_core#36]
I am trying to get an RTSP stream from a camera and show it in Unity. While searching the internet to find to see how can I do that, I have stumbled upon this project. So, may I ask these questions?

- Is it possible to integrate it into a Unity project to be built to Android?
- Is it possible to obtain video frames coming through RTSP protocol in Unity something like a byte array?

Kindest regards.

**Comment by mericgeren** [comment]
I am so sorry, I have created the issue on the wrong place. I am opening the issue at net7mma (non core) side.

**Comment by juliusfriedman** [comment]
I don't see why it would not be possible, if your using Rtsp and depacketizing the video then it's likely this library can help you especially if the video type is one which is implemented, e.g. MJPEG or H264 etc.

The .net core source code is slightly more up to do but this code should work fine as well.

Let me know what difficulties you run into and I will do whatever I can to help.

Sincerely.
