### ISSUE TITLE
Good to see you working on Net7MMA again

### ISSUE THREAD

**Issue by RogerHardiman** [juliusfriedman/net7mma_core#5]
Hi there
Just a quick note to say hello again and good to see you working on Net7MMA
We'd swapped several emails a few years back. I was doing streaming from Android and iPhones using the Mono/Xamarin tools. In the end I ended up working on SharpRTSP instead for that particular project.
But really glad to see Net7MMA getting some updates again.
I'll have to check it out and have a play.

(feel free to close this once you have read it)
Thanks
Roger Hardiman

**Comment by juliusfriedman** [comment]
See also: https://github.com/BogdanovKirill/RtspClientSharp

let me know if you have any issues.
